tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "awscli"
brew "gh"
brew "gradle"
brew "mas"
brew "micro"
brew "subversion"
brew "tig"
brew "zsh-autosuggestions"
brew "zsh-git-prompt"
brew "zsh-syntax-highlighting"
cask "appcleaner"
cask "aws-vpn-client"
cask "brave-browser-dev"
cask "corretto"
cask "figma"
cask "firefox"
cask "font-fira-code"
cask "font-lato"
cask "geekbench"
cask "iterm2"
cask "logitech-control-center"
cask "logitech-options"
cask "microsoft-auto-update"
cask "microsoft-edge-dev"
cask "microsoft-teams"
cask "postgres"
cask "postico"
cask "rectangle"
cask "slack"
cask "sourcetree"
cask "spotify"
cask "sublime-merge"
cask "sublime-text"
cask "telegram"
cask "visual-studio-code"
cask "vlc"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Microsoft Remote Desktop", id: 1295203466
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
